name: Continous Integration
on: [pull_request, workflow_dispatch]

jobs:
  install:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
     
  lint:
    name: Linting with ESLint
    runs-on: ubuntu-latest
    needs: [install]
    steps:
      - uses: actions/checkout@v2
        name: Lint
        id: eslint
#      - run: npm install
      - run: npm run lint sum.*
  test:
    name: Run unit tests with Jest
    runs-on: ubuntu-latest
    needs: [install, lint]
    steps:
      - uses: actions/checkout@v2
        name: Test
        id: jest
#      - run: npm install
      - run: npm run test
  format:
    name: Code Formatting with Prettier
    runs-on: ubuntu-latest
    needs: [install, lint, test]
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
        name: Format
#      - run: npm install
      - run: npm run format
      - name: Commit Change
        uses: stefanzweifel/git-auto-commit-action@v4.1.2
        with: 
          commit_message: Apply formatting changes
          branch: ${{ github.head_ref }}
