name: Continous Integration
on: [pull_request, workflow_dispatch]

jobs:
  lint:
    name: Linting with ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Lint
        id: eslint
        run: npm run lint sum.*
  test:
    name: Run unit tests with Jest
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Test
        id: jest
        run: npm run test
  format:
    name: Code Formatting with Prettier
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Install dependencies
        run: npm install
      - name: Format
        run: npm run format
      - name: Commit Change
        uses: stefanzweifel/git-auto-commit-action@v4.1.2
        with: 
          commit_message: Apply formatting changes
          branch: ${{ github.head_ref }}
