name: Continous Integration
on: [pull_request, workflow_dispatch]

jobs:
  test:
    name: Run unit tests with Jest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        name: Test
        id: jest
      - run: |
          npm install
          npm run test
  format:
    name: Code Formatting with Prettier
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Format
        run: |
          npm install
          npm run format
      - name: Commit Change
        uses: stefanzweifel/git-auto-commit-action@v4.1.2
        with: 
          commit_message: Apply formatting changes
          branch: ${{ github.head_ref }}
