name: Continous Integration
on: [pull_request, workflow_dispatch]

jobs:
  test:
    name: Run unit tests with Jest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        name: Test
        id: jest
      - run: |
          npm install
          npm run test
  format:
    name: Code Formatting with Prettier
    runs-on: ubuntu-latest
    if: success()
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        name: Format
      - run: |
          npm install
          npm run format
      - name: Commit Change
        uses: stefanzweifel/git-auto-commit-action@v4.1.2
        with: 
          commit_message: Apply formatting changes
          branch: ${{ github.head_ref }}
