name: Continous Integration
on: [pull_request, workflow_dispatch]

jobs:
  lint:
    name: Linting with ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hallee/eslint-action@1.0.3
        # GITHUB_TOKEN in forked repositories is read-only
        # https://help.github.com/en/actions/reference/events-that-trigger-workflows#pull-request-event-pull_request
        if: ${{ github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository }} 
        with:
          repo-token: ${{secrets.GITHUB_TOKEN}}
  test:
    name: Run unit tests with Jest
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - uses: actions/checkout@master
        name: Test
        id: jest
      - run: |
          npm install
          npm run test
  format:
    name: Code Formatting with Prettier
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Format
        run: |
          npm install
          npm run format
      - name: Commit Change
        uses: stefanzweifel/git-auto-commit-action@v4.1.2
        with: 
          commit_message: Apply formatting changes
          branch: ${{ github.head_ref }}
